[env:ATmega328P-XMINI]
platform = atmelavr
board = ATmega328P
board_build.f_cpu = 16000000L

platform_packages =
    tool-avrdude@1.70200.0

upload_protocol = custom
monitor_speed = 9600
monitor_echo = true

upload_flags =
    -C
    ${platformio.packages_dir}/tool-avrdude/avrdude.conf
    -p
    m328p
    -c
    xplainedmini
    -P
    usb

upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i